# Generated by Django 4.2.4 on 2023-08-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Reja nomi')),
                ('limit', models.DateTimeField(verbose_name='Tugash vaqti')),
            ],
        ),
    ]
